% DNA in pits User interface

function DNA_In_Pits_User_Interface()

Opts={'Import Videos', 'Grid Registration', 'Grid Fitting', 'Analysis',...
    'Signals and Visualization', 'Plots and Histograms'};
f=figure('MenuBar', 'None','Name', 'DNA In Pits User Interface', 'NumberTitle', 'off');
g = uimenu('Label','I am a test');
uimenu(g,'Label','I said I am a test !','Tag','WSOPT');
uimenu(g,'Label','Don''t you get it ?','Tag','COMPOPT');
uimenu('Label','Another test');

%============================ UICONTROLS ==================================
% add uicontextmenu
%'callback'
% button group
ButtonGroup=uibuttongroup('SelectionChangeFcn',@HandleMyVisibility);
uicontrol(ButtonGroup,'Style','radiobutton','Position',[10 475 300 100],...
    'String',Opts{1},'FontSize',14.0);
uicontrol(ButtonGroup,'Style','radiobutton','Position',[10 400 300 100],...
    'String',Opts{2},'FontSize',14.0);
uicontrol(ButtonGroup,'Style','radiobutton','Position',[10 325 300 100],...
    'String',Opts{3},'FontSize',14.0);
uicontrol(ButtonGroup,'Style','radiobutton','Position',[10 250 300 100],...
    'String',Opts{4},'FontSize',14.0);
uicontrol(ButtonGroup,'Style','radiobutton','Position',[10 175 300 100],...
    'String',Opts{5},'FontSize',14.0);
uicontrol(ButtonGroup,'Style','radiobutton','Position',[10 100 300 100],...
    'String',Opts{6},'FontSize',14.0);
set(ButtonGroup,'SelectedObject',[]);

uicontrol(f,'Style','pushbutton','Position',[10,625,300,50],...
    'String','Notepad','BackgroundColor','cyan',...
    'FontSize',12.0, 'callback',@OpenNotepad);
uicontrol(f,'Style','pushbutton','Position',[10,700,300,50],...
    'String','Blabla','BackgroundColor','yellow',...
    'FontSize',12.0)
uicontrol(f,'Style','pushbutton','Position',[10,775,300,50],...
    'String','Help','BackgroundColor','green',...
    'FontSize',12.0)

%========================== NOTEPAD =======================================
    function OpenNotepad(~,~)        
        defaultname=datestr(now,'yyyy mmmm dd HH MM SS AM');
        defaultname=strcat(defaultname,'.txt');
        [FileName,PathName] = uiputfile(defaultname);
        if ischar(FileName) && ischar(PathName)
            FileName=regexprep(FileName,'\.\w*','');
            FileName=strcat(FileName,'.txt');
           defaultname=fullfile(PathName,FileName); 
        end
        com=sprintf('notepad %s',defaultname);
        system(com);
    end
%==========================================================================

%------------------------- Handle Visibility ------------------------------
    function HandleMyVisibility(source,~)
        buttons=[Import_Videos,Grid_Registration,Grid_Fitting,...
            Analysis,Signals_And_Visualization,Plots_And_Histograms];
         buttonsprime={'Import Videos','Grid Registration','Grid Fitting',...
            'Analysis','Signals And Visualization','Plots And Histograms'};  
        ID=1:numel(buttonsprime);
       % PROBLEM
%         set(buttons(floor(callbackdata.NewValue)-floor(source)),'Visible','on');
%         set(buttons(floor(callbackdata.OldValue)-floor(source)),'Visible','off');
         stuff = get(source, 'children');
         names={stuff.String};
         Id=cellfun(@(x)strcmpi(x,buttonsprime),names,'uniformoutput',false);
         Id=cellfun(@(x)ID(x),Id,'Uniformoutput',false);
         if iscell(Id)
             Id=cell2mat(Id);
         end
         stuff=stuff(Id);         
         for i=1:numel(stuff)
            if get(stuff(i), 'value') == get(stuff(i), 'max')
                set(buttons(i),'Visible','on');
            else
                set(buttons(i),'Visible','off');
            end            
         end
    end
%--------------------------------------------------------------------------
%------------------------- IMPORT VIDEOS ----------------------------------
Import_Videos = uipanel('Title',Opts{1},'FontSize',12,...
    'BackgroundColor','white',...
    'Position',[.25 .1 .67 .67],'Visible','off');
uicontrol(Import_Videos,'Style','pushbutton','String',...
    'Get videos from server ...','Position',...
    [50.1,0.1,400,50],'FontSize',14,'BackgroundColor','cyan');
uicontrol(Import_Videos,'Style','pushbutton','String',...
    'Generate folder to analyze ...','Position',...
    [1050.1,0.1,200,50],'FontSize',14,'BackgroundColor','green',...
    'Callback',{@PleaseCall,'PutAllTifsTogether'});
uicontrol(Import_Videos,'Style','pushbutton','String',...
    'Import analyzed samples ...','Position',...
    [550.1,0.1,400,50],'FontSize',14,'BackgroundColor','yellow',...
    'Callback',{@PleaseCall,'ImportAnalyzedSamples'});
%--------------------------------------------------------------------------
%------------------------ GRID REGISTRATION -------------------------------

Grid_Registration = uipanel('Title',Opts{2},'FontSize',12,...
    'BackgroundColor','white',...
    'Position',[.25 .1 .67 .67],'Visible','off');
uicontrol(Grid_Registration,'Style','pushbutton','String',...
    'Register a grid ...','Position',...
    [50.1,0.1,400,50],'FontSize',14,'BackgroundColor','cyan',...
    'Callback',{@PleaseCall,'GridRegistration'});
uicontrol(Grid_Registration,'Style','pushbutton','String',...
    'Blabla ...','Position',...
    [550.1,0.1,400,50],'FontSize',14,'BackgroundColor','green');
uicontrol(Grid_Registration,'Style','pushbutton','String',...
    'Blabla ...','Position',...
    [1050.1,0.1,200,50],'FontSize',14,'BackgroundColor','yellow');
%--------------------------------------------------------------------------
%-------------------------- GRID FITTING ----------------------------------
Grid_Fitting = uipanel('Title',Opts{3},'FontSize',12,...
    'BackgroundColor','white',...
    'Position',[.25 .1 .67 .67],'Visible','off');
uicontrol(Grid_Fitting,'Style','pushbutton','String',...
    'Fit Grids ...','Position',...
    [50.1,0.1,400,50],'FontSize',14,'BackgroundColor','cyan',...
    'Callback',{@PleaseCall,'CheckPitGrids'});
uicontrol(Grid_Fitting,'Style','pushbutton','String',...
    'Check bad grids ...','Position',...
    [550.1,0.1,400,50],'FontSize',14,'BackgroundColor','green',...
    'Callback',{@PlaseCall,'CheckBadGrids'});
uicontrol(Grid_Fitting,'Style','pushbutton','String',...
    'Blabla ...','Position',...
    [1050.1,0.1,200,50],'FontSize',14,'BackgroundColor','yellow');
%--------------------------------------------------------------------------
%---------------------------- Analysis ----------------------------------

Analysis = uipanel('Title',Opts{4},'FontSize',12,...
    'BackgroundColor','white',...
    'Position',[.25 .1 .67 .67],'Visible','off');
uicontrol(Analysis,'Style','pushbutton','String',...
    'Analyze samples ...','Position',...
    [50.1,0.1,400,50],'FontSize',14,'BackgroundColor','cyan',...
    'Callback',{@PleaseCall,'DNA_In_Pits_Analysis'});
uicontrol(Analysis,'Style','pushbutton','String',...
    'Blabla ...','Position',...
    [550.1,0.1,400,50],'FontSize',14,'BackgroundColor','green');
uicontrol(Analysis,'Style','pushbutton','String',...
    'Blabla ...','Position',...
    [1050.1,0.1,200,50],'FontSize',14,'BackgroundColor','yellow');
%--------------------------------------------------------------------------
%--------------------------- FRET ANALYSIS --------------------------------

Signals_And_Visualization = uipanel('Title',Opts{5},'FontSize',12,...
    'BackgroundColor','white',...
    'Position',[.25 .1 .67 .67],'Visible','off');
uicontrol(Signals_And_Visualization,'Style','pushbutton','String',...
    'Look at each video ...','Position',...
    [50.1,0.1,400,50],'FontSize',14,'BackgroundColor','cyan',...
    'Callback',{@PleaseCall,'CheckSamplesOneByOne'});
uicontrol(Signals_And_Visualization,'Style','pushbutton','String',...
    'Save samples ...','Position',...
    [550.1,0.1,400,50],'FontSize',14,'BackgroundColor','green',...
    'Callback',{@PleaseCall,'SavePitSamples'});
uicontrol(Signals_And_Visualization,'Style','pushbutton','String',...
    'Blabla ...','Position',...
    [1050.1,0.1,200,50],'FontSize',14,'BackgroundColor','yellow');
%--------------------------------------------------------------------------
%------------------------ DIFFUSION/TRACKING ------------------------------

Plots_And_Histograms = uipanel('Title',Opts{6},'FontSize',12,...
    'BackgroundColor','white',...
    'Position',[.25 .1 .67 .67],'Visible','off');
uicontrol(Plots_And_Histograms,'Style','pushbutton','String',...
    'Poisson distributions ...','Position',...
    [50.1,0.1,400,50],'FontSize',14,'BackgroundColor','cyan',...
    'Callback',{@PleaseCall,'PoissonDistributions'});
uicontrol(Plots_And_Histograms,'Style','pushbutton','String',...
    'Binding histograms ...','Position',...
    [550.1,0.1,400,50],'FontSize',14,'BackgroundColor','green',...
    'Callback',{@PleaseCall,'ComplexFractionsBarPlot'});
uicontrol(Plots_And_Histograms,'Style','pushbutton','String',...
    'Blabla ...','Position',...
    [1050.1,0.1,200,50],'FontSize',14,'BackgroundColor','yellow');
%--------------------------------------------------------------------------
%==========================================================================
    function PleaseCall(~,~,myfunction)
        eval(myfunction);
    end

end

